#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🔍 Running ESLint..."
npx lint-staged --config .husky/lint-staged-tasks/.lintstagedrc.eslint.json || exit 1

echo "🎨 Formatting with Prettier..."
npx lint-staged --config .husky/lint-staged-tasks/.lintstagedrc.prettier.json || exit 1

echo "🧪 Running Tests..."
npx lint-staged --config .husky/lint-staged-tasks/.lintstagedrc.vitest.json || exit 1

echo "✅ All checks passed! Commit successful."
