name: "checkout-and-setup"
on: [push]
jobs:
  checkout-and-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
