name: "CI Workflow"
on: [push]
jobs:
  checkout-and-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install Packages
        run: yarn install

  run-eslint:
    runs-on: ubuntu-latest
    steps:
      - name: run linter
        run: yarn run lint

  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: run unit tests
        run: yarn run test
